# Generated by Django 5.2 on 2025-05-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('services', models.TextField(help_text='Comma-separated list, e.g., massage, dinner dates')),
                ('rates', models.CharField(help_text='Example: KES 5000/hr', max_length=100)),
                ('availability', models.CharField(help_text='Example: Mon-Fri, 10am-10pm', max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='escort_images/')),
                ('bio', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
