# Generated by Django 5.2 on 2025-05-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_escort_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escort',
            name='profile_image',
            field=models.ImageField(blank=True, default='escort_images/default.jpg', null=True, upload_to='escort_images/'),
        ),
    ]
