# Generated by Django 5.2 on 2025-05-04 10:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_escort_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escort',
            name='created_at',
        ),
        migrations.AddField(
            model_name='escort',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='escort',
            name='availability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='escort',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escort',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='escort',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='escort_images/'),
        ),
        migrations.AlterField(
            model_name='escort',
            name='rates',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='escort',
            name='services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escort',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, default=499.0, max_digits=10)),
                ('escort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='directory.escort')),
            ],
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
