# Generated by Django 5.2 on 2025-05-05 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_remove_escort_created_at_escort_average_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='end_date',
            new_name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='escort',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='escort',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='escort',
            name='availability',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='escort',
            name='bio',
            field=models.TextField(default='No bio provided'),
        ),
        migrations.AlterField(
            model_name='escort',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='escort',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='escort',
            name='rates',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='escort',
            name='services',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='escort',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='escort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.escort'),
        ),
    ]
